server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://app.cctfn.cn/pet_shop
    username: root
    password: reinhardt0524
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password: admin

ali:
  sms:
    accessId: jf8AxbvlHOfneEUv
    accessKey: 5OJWUG3RbcYpERQyZf88fww7UTgDSL
    signName: 唯物
    templateCode: SMS_141955090
    validTime: 600000